2024-05-09 10:27:51.391 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration bambu_lab which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-09 10:27:51.709 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //Users/haiyang.song/Develop/Python3Project/ha-bambulab/config/home-assistant_v2.db was shutdown cleanly
2024-05-09 10:27:51.734 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=12 from 2024-05-09 02:26:53.894191)
2024-05-09 10:27:52.776 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-1' coro=<setup_and_run_hass() running at /Users/haiyang.song/Develop/Python3Project/ha-bambulab/.venv/lib/python3.12/site-packages/homeassistant/runner.py:155> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py:712> cb=[_run_until_complete_cb() at /opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py:182] created at /opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py:695> took 0.296 seconds
2024-05-09 10:34:55.291 WARNING (MainThread) [asyncio] Executing <Handle shield.<locals>._inner_done_callback(<Task finishe.../tasks.py:420>) at /opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py:905 created at /opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py:88> took 422.033 seconds
